# Generated by Django 3.0.6 on 2020-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
                ('likes', models.CharField(max_length=300)),
                ('pic', models.CharField(max_length=300)),
            ],
        ),
    ]
