# Generated by Django 3.0.6 on 2020-05-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_artist_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pic',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
